name: create-master-merge-pr
on:
  workflow_dispatch
jobs:
  create-merge-pr:
    env:
      MERGE_BASE: main
      MERGE_FROM: release-1.0
      MERGE_INTO: auto-merge-into-master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch ${{ env.MERGE_BASE }}
        uses: actions/checkout@v2
        with:
          ref: ${{ env.MERGE_BASE }}
      - name: Push to pull request branch ${{ env.MERGE_INTO }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.MERGE_INTO }}
          force: true 
      - name: Merge branch ${{ env.MERGE_FROM }}
        uses: everlytic/branch-merge@1.1.0
        with: 
          source_ref: ${{ env.MERGE_FROM }}
          target_branch: ${{ env.MERGE_INTO }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message_template: "Automatic merge of ${{ env.MERGE_FROM }} into ${{ env.MERGE_BASE }}"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          base: ${{ env.MERGE_BASE }}
          branch: ${{ env.MERGE_FROM }}
