name: create-master-merge-pr
on:
  workflow_dispatch
jobs:
  create-merge-pr:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout master
          uses: actions/checkout@v2
          with:
            ref: main
        - name: Merge branch
          uses: devmasx/merge-branch@v1.3.1
          with: 
            type: now
            from_branch: release
            target_branch: merge-into-master
            github_token: ${{ github.token }}
